# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Flickr' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Moya'
  pod 'SnapKit'
  pod 'Kingfisher'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  # Pods for Flickr

end
